// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IFTextEncoderClient is an autogenerated mock type for the IFTextEncoderClient type
type IFTextEncoderClient struct {
	mock.Mock
}

// EncodeText provides a mock function with given fields: text
func (_m *IFTextEncoderClient) EncodeText(text string) ([]float32, error) {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for EncodeText")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]float32, error)); ok {
		return rf(text)
	}
	if rf, ok := ret.Get(0).(func(string) []float32); ok {
		r0 = rf(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIFTextEncoderClient creates a new instance of IFTextEncoderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFTextEncoderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFTextEncoderClient {
	mock := &IFTextEncoderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
