// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	textencoderpb "fast-search/internal/infrastructure/encoder/textencoderpb"
)

// TextEncoderServiceClient is an autogenerated mock type for the TextEncoderServiceClient type
type TextEncoderServiceClient struct {
	mock.Mock
}

// EncodeText provides a mock function with given fields: ctx, in, opts
func (_m *TextEncoderServiceClient) EncodeText(ctx context.Context, in *textencoderpb.TextRequest, opts ...grpc.CallOption) (*textencoderpb.VectorResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EncodeText")
	}

	var r0 *textencoderpb.VectorResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *textencoderpb.TextRequest, ...grpc.CallOption) (*textencoderpb.VectorResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *textencoderpb.TextRequest, ...grpc.CallOption) *textencoderpb.VectorResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*textencoderpb.VectorResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *textencoderpb.TextRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTextEncoderServiceClient creates a new instance of TextEncoderServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTextEncoderServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TextEncoderServiceClient {
	mock := &TextEncoderServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
