// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeTextEncoderServiceServer is an autogenerated mock type for the UnsafeTextEncoderServiceServer type
type UnsafeTextEncoderServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedTextEncoderServiceServer provides a mock function with given fields:
func (_m *UnsafeTextEncoderServiceServer) mustEmbedUnimplementedTextEncoderServiceServer() {
	_m.Called()
}

// NewUnsafeTextEncoderServiceServer creates a new instance of UnsafeTextEncoderServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeTextEncoderServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeTextEncoderServiceServer {
	mock := &UnsafeTextEncoderServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
