# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc  # type: ignore

import text_encoder_pb2 as text__encoder__pb2  # type: ignore


class TextEncoderServiceStub(object):
    """The text encoder service definition."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EncodeText = channel.unary_unary(
            "/textencoder.TextEncoderService/EncodeText",
            request_serializer=text__encoder__pb2.TextRequest.SerializeToString,
            response_deserializer=text__encoder__pb2.VectorResponse.FromString,
        )


class TextEncoderServiceServicer(object):
    """The text encoder service definition."""

    def EncodeText(self, request, context):
        """Sends a text to encode and receives the encoded vector."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TextEncoderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "EncodeText": grpc.unary_unary_rpc_method_handler(
            servicer.EncodeText,
            request_deserializer=text__encoder__pb2.TextRequest.FromString,
            response_serializer=text__encoder__pb2.VectorResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "textencoder.TextEncoderService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class TextEncoderService(object):
    """The text encoder service definition."""

    @staticmethod
    def EncodeText(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/textencoder.TextEncoderService/EncodeText",
            text__encoder__pb2.TextRequest.SerializeToString,
            text__encoder__pb2.VectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
