# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_encoder.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor  # type: ignore
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder  # type: ignore

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12text_encoder.proto\x12\x0btextencoder"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t" \n\x0eVectorResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32[\n\x12TextEncoderService\x12\x45\n\nEncodeText\x12\x18.textencoder.TextRequest\x1a\x1b.textencoder.VectorResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "text_encoder_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:  # noqa
    DESCRIPTOR._options = None
    _globals["_TEXTREQUEST"]._serialized_start = 35
    _globals["_TEXTREQUEST"]._serialized_end = 62
    _globals["_VECTORRESPONSE"]._serialized_start = 64
    _globals["_VECTORRESPONSE"]._serialized_end = 96
    _globals["_TEXTENCODERSERVICE"]._serialized_start = 98
    _globals["_TEXTENCODERSERVICE"]._serialized_end = 189
# @@protoc_insertion_point(module_scope)
