// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: text_encoder.proto

package textencoderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TextEncoderServiceClient is the client API for TextEncoderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextEncoderServiceClient interface {
	// Sends a text to encode and receives the encoded vector.
	EncodeText(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*VectorResponse, error)
}

type textEncoderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextEncoderServiceClient(cc grpc.ClientConnInterface) TextEncoderServiceClient {
	return &textEncoderServiceClient{cc}
}

func (c *textEncoderServiceClient) EncodeText(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*VectorResponse, error) {
	out := new(VectorResponse)
	err := c.cc.Invoke(ctx, "/textencoder.TextEncoderService/EncodeText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextEncoderServiceServer is the server API for TextEncoderService service.
// All implementations must embed UnimplementedTextEncoderServiceServer
// for forward compatibility
type TextEncoderServiceServer interface {
	// Sends a text to encode and receives the encoded vector.
	EncodeText(context.Context, *TextRequest) (*VectorResponse, error)
	mustEmbedUnimplementedTextEncoderServiceServer()
}

// UnimplementedTextEncoderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTextEncoderServiceServer struct {
}

func (UnimplementedTextEncoderServiceServer) EncodeText(context.Context, *TextRequest) (*VectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncodeText not implemented")
}
func (UnimplementedTextEncoderServiceServer) mustEmbedUnimplementedTextEncoderServiceServer() {}

// UnsafeTextEncoderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextEncoderServiceServer will
// result in compilation errors.
type UnsafeTextEncoderServiceServer interface {
	mustEmbedUnimplementedTextEncoderServiceServer()
}

func RegisterTextEncoderServiceServer(s grpc.ServiceRegistrar, srv TextEncoderServiceServer) {
	s.RegisterService(&TextEncoderService_ServiceDesc, srv)
}

func _TextEncoderService_EncodeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextEncoderServiceServer).EncodeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/textencoder.TextEncoderService/EncodeText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextEncoderServiceServer).EncodeText(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextEncoderService_ServiceDesc is the grpc.ServiceDesc for TextEncoderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextEncoderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "textencoder.TextEncoderService",
	HandlerType: (*TextEncoderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncodeText",
			Handler:    _TextEncoderService_EncodeText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "text_encoder.proto",
}
